# Generated by Django 6.0.3 on 2026-04-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCompany',
        ),
    ]
