# Generated by Django 6.0.3 on 2026-04-09 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='departmentuser',
            name='unique_user_department',
        ),
        migrations.DeleteModel(
            name='DepartmentUser',
        ),
    ]
