# Generated by Django 6.0.4 on 2026-04-08 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_active_remove_company_created_at_and_more'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='active',
        ),
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='message',
        ),
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'unique_together': {('company', 'department')},
            },
        ),
    ]
