# Generated by Django 6.0.4 on 2026-04-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_department_active_remove_department_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydepartment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
