# Generated by Django 6.0.4 on 2026-04-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Etiqueta')),
                ('color', models.CharField(max_length=7, verbose_name='Cor (Hexadecimal)')),
                ('online', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'label',
                'verbose_name_plural': 'label',
            },
        ),
    ]
