# Generated by Django 6.0.4 on 2026-04-30 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_delete_usercompany'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AddField(
            model_name='label',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Hexadecimal'),
        ),
    ]
