# Generated by Django 6.0.4 on 2026-04-30 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_delete_usercompany'),
        ('labels', '0002_alter_label_options_label_company_alter_label_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='companies.company'),
        ),
    ]
