# Generated by Django 6.0.4 on 2026-04-07 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name': 'Vínculo de Usuário', 'verbose_name_plural': 'Vínculos de Usuários'},
        ),
        migrations.AddField(
            model_name='usercompany',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
