# Generated by Django 6.0.4 on 2026-04-08 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_active_remove_company_created_at_and_more'),
        ('departments', '0002_remove_department_active_remove_department_company_and_more'),
        ('users', '0002_alter_usercompany_options_usercompany_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cellphone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logged_in_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logged_out_at',
        ),
        migrations.AddField(
            model_name='user',
            name='away_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='no_auto_assign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='see_department_tickets',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departamento do Usuário',
                'verbose_name_plural': 'Departamentos dos Usuários',
                'unique_together': {('user', 'department')},
            },
        ),
        migrations.DeleteModel(
            name='UserCompany',
        ),
    ]
