# Generated by Django 6.0.3 on 2026-04-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_updated_at'),
        ('users', '0002_user_is_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_users', to='clients.client'),
        ),
    ]
