# Generated by Django 6.0.4 on 2026-04-08 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_remove_profile_company_profile_active_and_more'),
        ('users', '0003_rename_cellphone_user_phone_remove_user_logged_in_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='permissions.profile'),
        ),
    ]
