# Generated by Django 6.0.3 on 2026-04-08 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_delete_usercompany'),
        ('departments', '0001_initial'),
        ('users', '0004_usercompany_delete_userclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='usercompany',
            name='unique_user_company',
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='no_auto_assign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='see_department_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='departments.department'),
        ),
        migrations.AddField(
            model_name='userdepartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userdepartment',
            unique_together={('user', 'department')},
        ),
        migrations.DeleteModel(
            name='UserCompany',
        ),
    ]
