# Generated by Django 6.0.4 on 2026-04-08 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companydepartment'),
        ('departments', '0003_companydepartment_active_department_active'),
        ('users', '0005_alter_userdepartment_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_access', to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_access', to='departments.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company', 'department')},
            },
        ),
    ]
