# Generated by Django 6.0.4 on 2026-04-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_online_user_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='absence_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem de Ausência'),
        ),
    ]
