# Generated by Django 6.0.4 on 2026-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usercompanydepartment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompanydepartment',
            options={'verbose_name': 'Vínculo Usuário , Empresa e Departamento', 'verbose_name_plural': 'Vínculo Usuário , Empresa e Departamento'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Status Online'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Logout'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Login'),
        ),
    ]
