# Generated by Django 6.0.4 on 2026-04-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_active_remove_company_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
