# Generated by Django 6.0.4 on 2026-04-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_active'),
        ('departments', '0003_companydepartment_active_department_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_departments', to='company.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='departments.department')),
            ],
            options={
                'verbose_name': 'Departamento da Empresa',
                'verbose_name_plural': 'Departamentos das Empresas',
                'unique_together': {('company', 'department')},
            },
        ),
    ]
