# Generated by Django 6.0.3 on 2026-04-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_updated_at'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='profilepermission',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_permissions', to='permissions.profile'),
        ),
    ]
