# Generated by Django 6.0.3 on 2026-04-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_profile_client_alter_profilepermission_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='client',
        ),
    ]
