# Generated by Django 6.0.4 on 2026-05-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_remove_profile_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='label',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
