# Generated by Django 6.0.4 on 2026-05-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_permission_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepermission',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilepermission',
            name='permission',
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['label'], 'verbose_name': 'Permissão', 'verbose_name_plural': 'Permissões'},
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfilePermission',
        ),
    ]
